# Site settings
title: Topophi
header-img: img/backpackers.jpg
email: info@topophi.com
description: "Find your outdoors"
baseurl: ""
url: "https://topophi.github.io" #TODO: Update to https://blog.topophi.com once we are live
mainSiteUrl: "http://topophi.bitbucket.org" #TODO: Update to https://www.topophi.com once we are live
twitter_username: gotopophi
facebook_username:  topophi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/page/:num/"
exclude: ["less","node_modules","Gruntfile.js","LICENSE","package.json","README.md"]

# Plugins (github blocks all 3rd party plugins, except for these)
gems:
- jekyll-sitemap
- jekyll-redirect-from