# Site settings
title: Topophi Blog
header-img: img/home-bg.jpg
email: blog@topophi.com
description: "Your #1 backpacking resource"
baseurl: ""
url: "http://topophi.github.io"
twitter_username: topophi
github_username:  topophi
facebook_username:  topophi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
