# Site settings
title: Topophi
pageTitle: Topophi Blog
header-img: img/backpackers.jpg
logo-img: img/logo.png
email: info@topophi.com
description: "Find your outdoors"
baseurl: ""
url: "https://blog.topophi.com"
mainSiteUrl: "https://www.topophi.com"
twitter_username: gotopophi
facebook_username:  topophi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/page/:num/"
exclude: ["less","node_modules","Gruntfile.js","LICENSE","package.json","README.md"]

# Plugins (github blocks all 3rd party plugins, except for these)
gems:
- jekyll-sitemap
- jekyll-redirect-from
